name: Go build

on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            
    test:
        runs-on: ubuntu-latest
        steps:
            - name: setup go env
              uses: actions/setup-go@v2
              with:
                  go-version: '1.15.1'
            - name: check-test
              uses: n8maninger/action-golang-test@v1
              with:
                args: "-race;-failfast;-tags=testing debug netgo"
            - run: go run hello-world.go